"""
GPT 프롬프트 템플릿 패키지
"""

from .quiz_prompts import (
    SYSTEM_PROMPT,
    QUIZ_GENERATION_PROMPT,
    SECTION_QUIZ_GENERATION_PROMPT,
    CONCEPT_EXTRACTION_PROMPT,
    ERROR_PROMPT
)

__all__ = [
    "SYSTEM_PROMPT",
    "QUIZ_GENERATION_PROMPT", 
    "SECTION_QUIZ_GENERATION_PROMPT",
    "CONCEPT_EXTRACTION_PROMPT",
    "ERROR_PROMPT"
] 